// Generated by Obsidian Export — Nubien - AI Agency & Studio (copy)
// Page: / · 02/07/2026
import './styles.css'


export default function () {
  return (
    <div style={{ background: '#000000', minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>

    </div>
  )
}
